# Example sitescan_config.yaml file
site1: http://webserver.myhost.com/path/to/examine
site2: http://www.anotherhost.org:8080/
site1user: someguy
site1pass: spaceballs12345
site1name: MyHost.com site
# site2user: 
# site2pass:
site2name: AnotherHost site
